---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=255.3
  sha1: 1a3d61f968b9719d9afbd160a02930c464958bf4
- name: bosh-aws-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=44
  sha1: a1fe03071e8b9bf1fa97a4022151081bf144c8bc

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3202
    sha1: ca5095fed22439a6238298aa0f8c578b0c11b87c
  cloud_properties:
    instance_type: m3.xlarge
    ephemeral_disk: {size: 25_000, type: gp2}
    availability_zone: us-west-1a # <--- Replace with Availability Zone

disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties: {type: gp2}

networks:
- name: private
  type: manual
  subnets:
  - range: 192.168.1.0/24
    gateway: 192.168.1.1
    dns: [8.8.8.8]
    cloud_properties: {subnet: subnet-b5296dd0} # <--- Replace with example Subnet ID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: redis, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: aws_cpi, release: bosh-aws-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [192.168.1.6]
    default: [dns, gateway]
  - name: public
    static_ips: [52.8.71.6] # <--- Replace with public Elastic IP address, from "aws ec2 allocate-address"

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    redis:
      listen_addresss: 127.0.0.1
      address: 127.0.0.1
      password: redis-password

    postgres: &db
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: 192.168.1.6
      host: 192.168.1.6
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: 192.168.1.6
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: aws_cpi
      max_threads: 10

    hm:
      director_account: {user: admin, password: admin}
      resurrector_enabled: true

    aws: &aws
      access_key_id: BLAHI6MBLAHV7HSBLAH # <--- Replace with AWS Access Key ID
      secret_access_key: BLAHRGt2ZBLAHzphlMjteGBLAHBLAHrGiCGiD1 # <--- Replace with AWS Secret Key
      default_key_name: ExampleKeyPair
      default_security_groups: [secg]
      region: us-west-1

    agent: {mbus: "nats://nats:nats-password@192.168.1.6:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: 52.8.71.6 # <--- Replace with Elastic IP address, same as above
    port: 22
    user: vcap
    private_key: ./ExampleKeyPair.pem # <--- Path to key must be relative to this manifest file

  mbus: "https://mbus:mbus-password@52.8.71.6:6868" # <--- Replace with Elastic IP address, retaining “:6868” port number

  properties:
    aws: *aws
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
