---
name: example-product-906ec4aecbec172c9706
director_uuid: ea1b4d3e-bc26-4e83-b7a0-dd3b08cb7089 # <----- Replace with BOSH director UUID from "bosh status --uuid"
releases:
- name: example-release
  version: '7+dev.2'
networks:
- name: default
  subnets:
  - range: 192.168.1.0/24
    gateway: 192.168.1.1
    dns:
    - 192.168.1.2
    static:
    - 192.168.1.7
    reserved:
    - 192.168.1.2 - 192.168.1.6
    cloud_properties:
      subnet: subnet-b5296dd0  # <----- Replace with example Subnet ID
resource_pools:
- name: vms
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: '3026'
  network: default
  cloud_properties:
    instance_type: t2.micro
    availability_zone: us-west-1a # <----- Replace with Availability Zone
    ephemeral_disk:
      size: 2048
      type: gp2
compilation:
  reuse_compilation_vms: true
  workers: 1
  network: default
  cloud_properties:
    instance_type: t2.micro
    availability_zone: us-west-1a  # <----- Replace with Availability zone
    ephemeral_disk:
      size: 2048
      type: gp2
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: true
jobs:
- name: web_server
  templates:
  - name: web_server
    release: example-release
  - name: time_logger
    release: example-release
  lifecycle: service
  instances: 1
  resource_pool: vms
  networks:
  - name: default
    default:
    - dns
    - gateway
    static_ips:
    - 192.168.1.7
  properties:
    max_in_flight: 1
  persistent_disk_pool: disk
disk_pools:
- name: disk
  disk_size: 1024
  cloud_properties:
    type: gp2
